export function renderPromptLayerScript(): string {
  return `      function renderPromptLayerDetails(options) {
        const role = options.role;
        const isToolRequest = role === "tool_request";
        const showsThinking = options.showsThinking ?? (role === "assistant" || isToolRequest);
        const showsContent = options.showsContent ?? !isToolRequest;
        const roleOptions = options.roleOptions || ["system", "user", "assistant", "tool_request"];
        return \`
          <details class="prompt-layer" \${options.attributes} open>
            <summary>\${escapeHtml(options.title || "Untitled Layer")}<span>[\${escapeHtml(role)}]\${options.enabled ? "" : " disabled"}</span></summary>
            <div class="row">
              <div>
                <label>Title</label>
                <input data-field="title" value="\${escapeAttr(options.title || "")}" />
              </div>
              <div>
                <label>Role</label>
                <select data-field="role">
                  \${roleOptions.map((item) => \`<option value="\${item}" \${role === item ? "selected" : ""}>\${item}</option>\`).join("")}
                </select>
              </div>
              <div>
                <label>Name</label>
                <input data-field="name" value="\${escapeAttr(options.name || "")}" />
              </div>
              <label><input data-field="enabled" type="checkbox" \${options.enabled ? "checked" : ""} /> Enabled</label>
            </div>
            \${isToolRequest ? \`
            <label>Tool Calls JSON</label>
            <textarea data-field="toolCalls" rows="7">\${escapeHtml(JSON.stringify(cloneToolCalls(options.toolCalls), null, 2))}</textarea>
            <p class="muted">\${escapeHtml(options.toolHint || "Tool result is generated by actually running this request when the LLM request is built. It is not editable.")}</p>\` : ""}
            \${showsThinking ? \`<label>\${isToolRequest ? "Thinking / Assistant Tool Call Content" : "Thinking / Assistant Content"}</label>
            <textarea data-field="thinking" rows="3">\${escapeHtml(options.thinking || "")}</textarea>\` : ""}
            \${showsContent ? \`<label>Content</label>
            <textarea data-field="content" rows="7">\${escapeHtml(options.content || "")}</textarea>\` : ""}
            <div class="prompt-actions">
              <button type="button" data-action="up" \${options.index === 0 ? "disabled" : ""}>Up</button>
              <button type="button" data-action="down" \${options.index === options.count - 1 ? "disabled" : ""}>Down</button>
              <button type="button" data-action="delete" class="secondary">Delete</button>
            </div>
          </details>
        \`;
      }

      function cloneToolCalls(toolCalls) {
        if (!Array.isArray(toolCalls)) return [];
        return toolCalls.map((call) => ({
          toolName: String(call && call.toolName || ""),
          ...(call && call.toolCallId ? { toolCallId: String(call.toolCallId) } : {}),
          toolArguments: typeof (call && call.toolArguments) === "string" ? call.toolArguments : "{}"
        }));
      }

      function updateToolCallsFromTextarea(layer, value, onValid) {
        try {
          const parsed = JSON.parse(value);
          if (!Array.isArray(parsed)) return;
          layer.toolCalls = cloneToolCalls(parsed);
          onValid?.();
        } catch {
          return;
        }
      }
`;
}
